

# SYSTEM PERMISSIONS
SYSTEM_PERMISSION_INSERT = 'SYS_PER_INSERT'
SYSTEM_PERMISSION_UPDATE = 'SYS_PER_UPDATE'
SYSTEM_PERMISSION_DELETE = 'SYS_PER_DELETE'
SYSTEM_PERMISSION = (SYSTEM_PERMISSION_INSERT,SYSTEM_PERMISSION_UPDATE,SYSTEM_PERMISSION_DELETE)

# SYSTEM STATES
SYSTEM_STATE_ACTIVE = 'SYS_STATE_ACTIVE'
SYSTEM_STATE_DELETED = 'SYS_STATE_DELETED'
SYSTEM_STATE = (SYSTEM_STATE_ACTIVE,SYSTEM_STATE_DELETED)
#DEFAULT USER SYSTEM

#ENTITY
SYSTEM_ENTITY = 'SystemInit'

# GROUP TYPE
SYSTEM_GROUPTYPE = 'SystemInit'
SYSTEM_GROUP = 'SystemInit'
SYSTEM_INIT_USER = 'SystemInit1@init.com'
SYSTEM_LOGINTYPE = 'SystemInit'

# INITIALISATION USERNAME AND PASSWORD
SYSTEM_INITIALISE_USERNAME = 'tx2'
SYSTEM_INITIALISE_PASSWORD = 'tx2'

# LOGGER NAME
SYSTEM_INITIALISE_LOGGER = 'SYSTEM_INITIALISE_LOGGER'

#MISC
SYSTEM_INITIALISE_SESSION_NAME = 'AdminInitLoginSession'

